#!/bin/sh
#
# Runs during git flow release start
#
# Positional arguments:
# $1    Version
#
# Return VERSION - When VERSION is returned empty gitflow
#	will stop as the version is necessary
#
VERSION=$1

# Implement your script here.
. "$HOOKS_DIR"/gitflow-functions
ROOTDIR=$(git rev-parse --show-toplevel)

gitflow_set_major_minor $VERSION
AVH_PATCH_LEVEL=$(($AVH_PATCH_LEVEL+1))
git checkout -q $current_branch

gitflow_build_version

# Return the VERSION
echo ${AVH_VERSION}
exit 0
